# Generated by Django 4.0.4 on 2022-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questions_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
