# Generated by Django 4.0.4 on 2022-07-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guidelines_data_alter_guidelines_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidelines',
            old_name='data',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='help',
            new_name='helpdata',
        ),
    ]
