# Generated by Django 4.0.4 on 2022-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_data_guidelines_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slnum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
