# Generated by Django 4.0.4 on 2022-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_questions_slnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='helpdata',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
