# Generated by Django 4.0.4 on 2022-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_questions_helpdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoredata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
