# Generated by Django 4.0.4 on 2022-09-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scoredata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slnum', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('helpdata', models.CharField(blank=True, max_length=500)),
                ('answer', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
