# Generated by Django 4.0.4 on 2022-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answerdata_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='id',
        ),
        migrations.AlterField(
            model_name='score',
            name='username',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
