# Generated by Django 4.0.4 on 2022-09-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_answerdata_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Scores',
        ),
    ]
