# Generated by Django 4.0.4 on 2022-09-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_score_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='helpdata',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scores',
            name='username',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
