# Generated by Django 4.0.4 on 2022-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_scores_id_alter_questions_helpdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.RemoveField(
            model_name='scoredata',
            name='desc',
        ),
        migrations.AddField(
            model_name='scoredata',
            name='username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
