# Generated by Django 4.0.4 on 2022-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_scores_remove_scoredata_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdata',
            name='helpdata',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
